[
  ./ci-agent
  ./core
  ./db/postgres
  ./develop
  ./develop/kakoune
  ./develop/python
  ./develop/tmux
  ./develop/zsh
  ./graphical
  ./graphical/games
  ./graphical/im
  ./graphical/plex.nix
  ./graphical/qutebrowser
  ./graphical/sway
  ./graphical/xmonad
  ./laptop
  ./misc/disable-mitigations.nix
  ./network
  ./network/adblocking.nix
  ./network/networkmanager
  ./network/stubby.nix
  ./network/torrent.nix
  ./ssh
  ./virt
]
