# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  manix = {
    pname = "manix";
    version = "v0.6.3";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "v0.6.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
    
  };
}
