# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  dotenv = {
    pname = "dotenv";
    version = "1.0.1";
    src = fetchurl {
      url = "https://open-vsx.org/api/mikestead/dotenv/1.0.1/file/mikestead.dotenv-1.0.1.vsix";
      sha256 = "1ilp720bakyqwb29cxs1k7xsbqlill5j8dnk6bm839xzdvy394sk";
    };
    homepage = "https://github.com/mikestead/vscode-dotenv";
    license = "mit";
    description = "Support for dotenv file syntax";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  nixpkgs-fmt = {
    pname = "nixpkgs-fmt";
    version = "0.0.1";
    src = fetchurl {
      url = "https://B4dM4n.gallery.vsassets.io/_apis/public/gallery/publisher/B4dM4n/extension/nixpkgs-fmt/0.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      sha256 = "1gvjqy54myss4w1x55lnyj2l887xcnxc141df85ikmw1gr9s8gdz";
    };
    license = "mit";
  };
  rust = {
    pname = "rust";
    version = "0.7.8";
    src = fetchurl {
      url = "https://open-vsx.org/api/rust-lang/rust/0.7.8/file/rust-lang.rust-0.7.8.vsix";
      sha256 = "02mpqpyk6aid6s7byqzh8s1fd2mgzcpl2rpyri0fgakc67bsnyz6";
    };
    homepage = "https://github.com/rust-lang/rls-vscode";
    license = "[ \"mit\", \"asl20\" ]";
    description = "Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer). Provides lints, code completion and navigation, formatting and more.";
  };
}
